const data = [
  {
    handle: "Ana",
    timeZone: "Pacific Time",
    favCity: "Los Angeles, California",
    favColor: "#FF69B4",
    favTheme: "Light mode",
    favLang: "CSS",
    favSnack: "Something Salty",
    favMusic: "Instrumental only",
    imgSrc: "../Images/fruits1.jpg",
  },
  {
    handle: "Andrea",
    timeZone: "Pacific Time",
    favCity: "New York, New York",
    favColor: "#008080",
    favTheme: "Dark mode",
    favLang: "JavaScript",
    favSnack: "None",
    favMusic: "Instrumental only",
    imgSrc: "../Images/fruits2.jpg",
  },
  {
    handle: "Jesoul",
    timeZone: "Eastern Time",
    favCity: "New York, New York",
    favColor: "red",
    favTheme: "Light mode",
    favLang: "jQuery",
    favSnack: "Something Umami",
    favMusic: "No music",
    imgSrc: "../Images/fruits3.jpg",
  },
  {
    handle: "Kalevtutar",
    timeZone: "Eastern Time",
    favCity: "Anchorage, Alaska",
    favColor: "purple",
    favTheme: "Dark mode",
    favLang: "React.js",
    favSnack: "Something Sweet",
    favMusic: "No music",
    imgSrc: "../Images/fruits4.jpg",
  },
  {
    handle: "LottaMonet",
    timeZone: "Pacific Time",
    favCity: "Chicago, Illinois",
    favColor: "yellow",
    favTheme: "Dark mode",
    favLang: "JavaScript",
    favSnack: "Something Salty",
    favMusic: "Vocals + Instrumental",
    imgSrc: "../Images/fruits5.jpg",
  },
  {
    handle: "MJ",
    timeZone: "Pacific Time",
    favCity: "Portland, Oregon",
    favColor: "#32CD32",
    favTheme: "Dark mode",
    favLang: "JavaScript",
    favSnack: "Something Sweet",
    favMusic: "Instrumental only",
    imgSrc: "../Images/fruits6.jpg",
  },
  {
    handle: "Morys",
    timeZone: "Central Time",
    favCity: "New York, New York",
    favColor: "brown",
    favTheme: "Dark mode",
    favLang: "CSS",
    favSnack: "Something Umami",
    favMusic: "Instrumental only",
    imgSrc: "../Images/fruits7.jpg",
  },
  {
    handle: "Nocturne",
    timeZone: "Central Time",
    favCity: "Los Angeles, California",
    favColor: "#CCCCFF",
    favTheme: "Dark mode",
    favLang: "CSS",
    favSnack: "Some combo delight",
    favMusic: "Instrumental only",
    imgSrc: "../Images/fruits8.jpg",
  },
  {
    handle: "Tberry",
    timeZone: "Central Time",
    favCity: "Austin, Texas",
    favColor: "tan",
    favTheme: "Dark mode",
    favLang: "CSS",
    favSnack: "Some combo delight",
    favMusic: "Vocals only",
    imgSrc: "../Images/fruits9.jpg",
  },
  {
    handle: "VuduQueen",
    timeZone: "Eastern Time",
    favCity: "Honolulu, Hawaii",
    favColor: "black",
    favTheme: "Dark mode",
    favLang: "HTML",
    favSnack: "Something Salty",
    favMusic: "Vocals + Instrumental",
    imgSrc: "../Images/fruits10.jpg",
  },
];
